In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [27]:
np.random.seed(42)

In [28]:
df = pd.DataFrame({
    'Student_ID' : range(1,101),
    'Name' : [f'Student_{i}' for i in range (1,101)],
    'Gender' : np.random.choice(['Male','Female'],100),
    'Department' : np.random.choice(['CSE' ,'ME','ECE','CE'],100),
    'Marks' : np.random.randint(40,101,100)
})

In [29]:
df

    Student_ID         Name  Gender Department  Marks
0            1    Student_1    Male        ECE     71
1            2    Student_2  Female         ME     78
2            3    Student_3    Male         ME     88
3            4    Student_4    Male         CE     91
4            5    Student_5    Male         ME    100
..         ...          ...     ...        ...    ...
95          96   Student_96  Female         ME     92
96          97   Student_97  Female         ME     83
97          98   Student_98  Female         CE     65
98          99   Student_99  Female        CSE     71
99         100  Student_100    Male        ECE     45

[100 rows x 5 columns]

In [30]:
df.head()

   Student_ID       Name  Gender Department  Marks
0           1  Student_1    Male        ECE     71
1           2  Student_2  Female         ME     78
2           3  Student_3    Male         ME     88
3           4  Student_4    Male         CE     91
4           5  Student_5    Male         ME    100

In [31]:
print("Populatin size :",len(df))

Populatin size : 100

In [32]:
print("Department Distribution :")
print(df['Department'].value_counts())
print("\nGender Distribution :")
print(df['Gender'].value_counts())

Department Distribution :
Department
ECE    30
CSE    26
CE     24
ME     20
Name: count, dtype: int64

Gender Distribution :
Gender
Female    56
Male      44
Name: count, dtype: int64

In [33]:
sample_size = 10
simple_random_sample = df.sample(
    n=sample_size,
    random_state=42
)simple_random_sample

SyntaxError: invalid syntax (175179630.py, line 5)

In [ ]:
sample_size = 10

simple_random_sample = df.sample(
    n=sample_size,
    random_state=42
)

simple_random_sample

In [ ]:
plt.figure(figsize=(7,4))
plt.scatter(df['Student_ID'], df['Marks'] , alpha=0.35 ,label='Population')
plt.scatter(simple_random_sample['Student_ID'],
            simple_random_sample['Marks'],
            s=120,label='Selected Sample')
plt.xlabel("Student ID")
plt.ylabel("Marks")
plt.title("Visualization")
plt.legend()
plt.show()

In [ ]:
#2.systemic sampling
N = len(df) #Length of Population
n = 10  #no of interval
k=N //n #No of data which need to retrive from
start = np.random.randint(0,k)
systematic_sample=df.iloc[start::k].head(n)

print("Sampling Interval :",k)
print("Starting position :",start)
systematic_sample

In [ ]:
plt.figure(figsize=(7,4))
plt.scatter(df['Student_ID'], df['Marks'] , alpha=0.35 ,label='Population')
plt.scatter(systematic_sample['Student_ID'],
            systematic_sample['Marks'],
            s=120,label='Selected Sample')
plt.xlabel("Student ID")
plt.ylabel("Marks")
plt.title("Systematic Samling")
plt.legend()
plt.show()

In [ ]:
#Stratified Sampling
sample_size=20
stratified_sample,remining = train_test_split(
    df,
    test_size=0.80,
    stratify=df['Department'],
    random_state = 42
)
stratified_sample

In [ ]:
print("Original Department Proportion:")
print(df['Department'].value_counts(normalize = True).round(2))
print("\nSample Proportion :")
print(stratified_sample['Department'].value_counts(normalize = True).round(2))

#visualization of stratified sample
comparison =pd.DataFrame({
    'Population' : df['Department'].value_counts(),
    'Sample' :stratified_sample['Department'].value_counts
})
comparison.plot(kind ='bar',figsize=(8,4))
plt.title("Population VS Sample -: Stratified Sampling")
plt.xlabel("Department")
plt.ylabel("No of students")
plt.show()

In [ ]:
#Cluster Sampling
cluster = df['Department'].unique()
selected_clusters = np.random.choice(
    cluster,
    size=2,
    replace=False
)
cluster_sample = df[
    df['Department'].isin(selected_clusters)
]
print("Selected Cluster :",selected_clusters)
print("Sample size :",len(cluster_sample))
cluster_sample.head(5)

In [ ]:
#Visulization of cluster Sampling
plt.figure(figsize=(12,5))
plt.scatter(df['Student_ID'], df['Marks'] , alpha=0.35 ,label='Population')
plt.scatter(systematic_sample['Student_ID'],
            systematic_sample['Marks'],
            s=120,label='Selected Sample')
plt.xlabel("Student ID")
plt.ylabel("Marks")
plt.title("Systematic Samling")
plt.legend()
plt.show()

In [ ]:
#Quota sampling
male_sample =df[df['Gender'] == 'Male'].sample(
    n=5 ,random_state=42
)
female_sample=df[df['Gender'] == 'Female'].sample(
    n=5,random_state=42
)
quota_sample=pd.concat([
    male_sample,female_sample
])
print(quota_sample['Gender'].value_counts())

In [ ]:
#Visualization of Quota_Sample
quota_counts = quota_sample['Gender'].value_counts()
quota_counts.plot(kind='bar',figsize=(8,5))
plt.title("Quota  Sample by Gender wise")
plt.xlabel("Gender")
plt.ylabel("No. of Students")
plt.xticks(rotation=0)
plt.show()

In [ ]:
#convenince Sampling
conv_sample = df.head(10)
conv_sample